# Generated by Codex on 2026-07-06

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def create_default_spaces_and_assign_documents(apps, schema_editor) -> None:
    tenant_model = apps.get_model("tenancy", "Tenant")
    document_model = apps.get_model("documents", "Document")
    document_space_model = apps.get_model("documents", "DocumentSpace")

    for tenant in tenant_model.objects.all():
        general_space, _created = document_space_model.objects.get_or_create(
            tenant=tenant,
            path="/allgemein",
            defaults={
                "name": "Allgemein",
                "slug": "allgemein",
                "parent": None,
                "description": "",
                "space_kind": "general",
                "is_active": True,
            },
        )
        document_model.objects.filter(tenant=tenant, space__isnull=True).update(
            space=general_space
        )


def noop_reverse(apps, schema_editor) -> None:
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=80)),
                ("path", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "space_kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("invoices", "Invoices"),
                            ("personnel", "Personnel"),
                            ("contracts", "Contracts"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="documents.documentspace",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_spaces",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentspace",
            constraint=models.UniqueConstraint(
                fields=("tenant", "path"),
                name="unique_tenant_document_space_path",
            ),
        ),
        migrations.AddIndex(
            model_name="documentspace",
            index=models.Index(
                fields=["tenant", "parent"],
                name="documents_d_tenant__7e77dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentspace",
            index=models.Index(
                fields=["tenant", "is_active"],
                name="documents_d_tenant__af27ef_idx",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="space",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documentspace",
            ),
        ),
        migrations.RunPython(
            create_default_spaces_and_assign_documents,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name="document",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documentspace",
            ),
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="documents_d_tenant__7b56de_idx",
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "space"],
                name="documents_d_tenant__7f6353_idx",
            ),
        ),
    ]
