# Generated by Django 5.2.15 on 2026-07-06 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttag_documenttagassignment_documentcomment_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('multiline_text', 'Mehrzeiliger Text'), ('date', 'Datum'), ('number', 'Zahl'), ('boolean', 'Ja/Nein'), ('choice', 'Auswahl')], default='text', max_length=30)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_fields', to='documents.documentspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_metadata_fields', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['space__path', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'space', 'is_active'], name='documents_d_tenant__437658_idx'), models.Index(fields=['tenant', 'slug'], name='documents_d_tenant__426176_idx')],
                'constraints': [models.UniqueConstraint(fields=('space', 'slug'), name='unique_document_box_metadata_field_slug')],
            },
        ),
    ]
