# Generated by Django 5.2.15 on 2026-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_einvoice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadatafield',
            name='einvoice_source',
            field=models.CharField(blank=True, choices=[('', 'Keine automatische Übernahme'), ('invoice_number', 'Rechnungsnummer'), ('invoice_date', 'Rechnungsdatum'), ('seller_name', 'Verkäufer'), ('buyer_name', 'Käufer'), ('currency', 'Währung'), ('line_total_amount', 'Zeilensumme netto'), ('tax_basis_total_amount', 'Steuerbasis gesamt'), ('tax_total_amount', 'Steuerbetrag gesamt'), ('grand_total_amount', 'Gesamtbetrag'), ('due_payable_amount', 'Zahlbetrag'), ('tax_breakdown_summary', 'Steueraufteilung'), ('tax_net_0', 'Netto 0 %'), ('tax_net_7', 'Netto 7 %'), ('tax_net_19', 'Netto 19 %'), ('tax_amount_7', 'Steuer 7 %'), ('tax_amount_19', 'Steuer 19 %')], default='', max_length=80),
        ),
    ]
