# Generated by Django 5.2.15 on 2026-07-08 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentmetadatafield_allow_custom_choices'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status', '-created_at', '-id'], name='documents_d_tenant__4a07cd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'space', 'status', '-created_at', '-id'], name='documents_d_tenant__123be7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'document_date', '-created_at', '-id'], name='documents_d_tenant__1bfea1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['tenant', 'document', 'file_kind', '-version'], name='documents_d_tenant__120a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['tenant', 'sha256', 'byte_size', 'file_kind'], name='documents_d_tenant__391dfa_idx'),
        ),
    ]
