# Generated by Django 5.2.15 on 2026-07-13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0014_documentfile_thumbnail_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcomment",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_document_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
