# Generated by Django 5.2.15 on 2026-07-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_documentcomment_mentioned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentspace',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_document_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentspace',
            name='deleted_strategy',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
