# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_documentspace_deleted_at_documentspace_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="file_kind",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("derivative", "Derivative"),
                    ("preview", "Vorschau"),
                    ("thumbnail", "Thumbnail"),
                ],
                default="original",
                max_length=20,
            ),
        ),
    ]
