# Generated by Codex on 2026-07-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_document_import_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_first",
                        to="documents.document",
                    ),
                ),
                (
                    "second_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_second",
                        to="documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_relations",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "first_document"],
                        name="documents_d_tenant__91d4fa_idx",
                    ),
                    models.Index(
                        fields=["tenant", "second_document"],
                        name="documents_d_tenant__a02a1d_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="documents_d_tenant__e08d0c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_document", "second_document"),
                        name="unique_document_relation_pair",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(
                            first_document=models.F("second_document")
                        ),
                        name="document_relation_distinct_documents",
                    ),
                ],
            },
        ),
    ]
