# Generated by Django 5.2.15 on 2026-07-23 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_remove_documentrelation_note'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBoxScanOptimizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_children', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=30)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('processed_documents', models.PositiveIntegerField(default=0)),
                ('last_document_id', models.PositiveIntegerField(default=0)),
                ('max_document_id', models.PositiveIntegerField(default=0)),
                ('candidates', models.PositiveIntegerField(default=0)),
                ('optimized', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('bytes_before', models.PositiveBigIntegerField(default=0)),
                ('bytes_after', models.PositiveBigIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='documentboxscanoptimizationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_optimization_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentboxscanoptimizationjob',
            name='document_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_optimization_jobs', to='documents.documentspace'),
        ),
        migrations.AddField(
            model_name='documentboxscanoptimizationjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_box_scan_optimization_jobs', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='documentboxscanoptimizationjob',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='documents_d_tenant__44773c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentboxscanoptimizationjob',
            index=models.Index(fields=['tenant', 'document_space', 'status'], name='documents_d_tenant__b55481_idx'),
        ),
    ]
