# Generated by Django 5.2.15 on 2026-07-23 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_document_title_einvoice_strategy"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBoxTitleRefreshJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_children", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Wartet"),
                            ("running", "Läuft"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("total_documents", models.PositiveIntegerField(default=0)),
                ("processed_documents", models.PositiveIntegerField(default=0)),
                ("last_document_id", models.PositiveIntegerField(default=0)),
                ("max_document_id", models.PositiveIntegerField(default=0)),
                ("updated_titles", models.PositiveIntegerField(default=0)),
                ("unchanged_titles", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("batch_size", models.PositiveIntegerField(default=100)),
                ("rule_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_title_refresh_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_refresh_jobs",
                        to="documents.documentspace",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_box_title_refresh_jobs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="documents_d_tenant__f4e0d9_idx",
                    ),
                    models.Index(
                        fields=["tenant", "document_space", "status"],
                        name="documents_d_tenant__614e32_idx",
                    ),
                ],
            },
        ),
    ]
