# Generated by Django 5.2.15 on 2026-07-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_documentboxtitlerefreshjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttitlerule',
            name='invoice_ocr_fallback_strategy',
            field=models.CharField(choices=[('automatic', 'OCR-Automatik'), ('regex', 'OCR-RegEx'), ('disabled', 'Dateiname beibehalten')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttitlerule',
            name='invoice_ocr_format',
            field=models.CharField(blank=True, default='{seller_name:.12}: {invoice_number}{invoice_date_suffix}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='documenttitlerule',
            name='fallback_strategy',
            field=models.CharField(choices=[('automatic', 'OCR-Automatik'), ('invoice_ocr', 'OCR-Rechnungsbeleg'), ('regex', 'OCR-RegEx'), ('disabled', 'Dateiname beibehalten')], default='automatic', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttitlerule',
            name='strategy',
            field=models.CharField(choices=[('automatic', 'Automatisch aus dem OCR-Volltext'), ('regex', 'RegEx auf dem OCR-Volltext'), ('einvoice', 'Aus eRechnungsdaten'), ('invoice_ocr', 'Rechnungsbeleg aus OCR'), ('disabled', 'Keine automatische Titelfindung')], default='automatic', max_length=20),
        ),
    ]
