# Generated by Django 5.2.15 on 2026-07-26 20:50

from django.db import migrations, models


def migrate_title_rule_scopes(apps, schema_editor):
    DocumentTitleRule = apps.get_model("documents", "DocumentTitleRule")
    for rule in DocumentTitleRule.objects.all().iterator():
        if rule.document_space_id is None:
            rule.is_default = True
            rule.save(update_fields=["is_default"])
        else:
            rule.document_spaces.add(rule.document_space_id)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_documenttitlerule_invoice_ocr_fallback_strategy_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttitlerule',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='documenttitlerule',
            name='unique_tenant_document_space_title_rule',
        ),
        migrations.RemoveConstraint(
            model_name='documenttitlerule',
            name='unique_tenant_default_title_rule',
        ),
        migrations.RemoveIndex(
            model_name='documenttitlerule',
            name='documents_d_tenant__4c022c_idx',
        ),
        migrations.AddField(
            model_name='documenttitlerule',
            name='document_spaces',
            field=models.ManyToManyField(blank=True, related_name='title_rules', to='documents.documentspace'),
        ),
        migrations.AddField(
            model_name='documenttitlerule',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            migrate_title_rule_scopes,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='documenttitlerule',
            name='document_space',
        ),
        migrations.AddConstraint(
            model_name='documenttitlerule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='unique_tenant_default_title_rule'),
        ),
    ]
