# Generated by Django 5.2.15 on 2026-07-27 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_documenttitlerule_options_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNavigationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_key', models.CharField(max_length=64)),
                ('document_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_navigation_contexts', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_navigation_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user', '-updated_at'], name='documents_d_tenant__58e4e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'source_key'), name='documents_unique_navigation_source')],
            },
        ),
    ]
