# Generated by Django 5.2.15 on 2026-07-27 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_documentnavigationcontext'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOfficeConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Wartet'), ('running', 'Läuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('auto_start_ocr', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_conversion_jobs', to=settings.AUTH_USER_MODEL)),
                ('output_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_conversion_outputs', to='documents.documentfile')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_conversion_jobs', to='documents.documentfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_conversion_jobs', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='documents_d_tenant__304ce7_idx'), models.Index(fields=['tenant', 'source_file', 'created_at'], name='documents_d_tenant__714b91_idx')],
            },
        ),
    ]
