# Generated by Django 5.2.15 on 2026-07-29 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_documentnavigationcontext_query_fields'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspace',
            name='advanced_review_assist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentReviewMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('symbol', models.CharField(choices=[('check', 'Schwarzer Haken'), ('exclamation', 'Rotes Ausrufezeichen'), ('question', 'Gelbes Fragezeichen')], max_length=30)),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('size', models.FloatField(default=0.045, validators=[django.core.validators.MinValueValidator(0.015), django.core.validators.MaxValueValidator(0.15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_review_markers', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_markers', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_review_markers', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['page_number', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'document', 'page_number'], name='documents_d_tenant__492421_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1)), name='documents_review_marker_x_range'), models.CheckConstraint(condition=models.Q(('y__gte', 0), ('y__lte', 1)), name='documents_review_marker_y_range'), models.CheckConstraint(condition=models.Q(('size__gte', 0.015), ('size__lte', 0.15)), name='documents_review_marker_size_range')],
            },
        ),
    ]
