# Generated by Django 5.2.15 on 2026-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_documentboxocrlayoutjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadatafield',
            name='propagate_to_child_spaces',
            field=models.BooleanField(default=True),
        ),
    ]
