# Generated by Django 5.2.15 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_public_mention_groups'),
        ('documents', '0037_metadata_field_propagation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='mentioned_roles',
            field=models.ManyToManyField(blank=True, related_name='mentioned_document_comments', to='accounts.tenantrole'),
        ),
    ]
