# Generated by Codex on 2026-07-06

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

PERMISSIONS = [
    ("documents.view", "Dokumente anzeigen", "Dokumente", 10),
    ("documents.upload", "Dokumente hochladen", "Dokumente", 20),
    ("documents.download", "Dokumente herunterladen", "Dokumente", 30),
    ("document_spaces.manage", "Dokumentenboxen verwalten", "Einstellungen", 40),
    ("settings.view", "Einstellungen anzeigen", "Einstellungen", 50),
    ("settings.members.manage", "Mitglieder verwalten", "Einstellungen", 60),
    ("settings.roles.manage", "Rollen verwalten", "Einstellungen", 70),
    ("audit.view", "Audit anzeigen", "Einstellungen", 80),
]

DEFAULT_ROLE_PERMISSIONS = {
    "admin": {
        "documents.view",
        "documents.upload",
        "documents.download",
        "document_spaces.manage",
        "settings.view",
        "settings.members.manage",
        "settings.roles.manage",
        "audit.view",
    },
    "member": {
        "documents.view",
        "documents.upload",
        "documents.download",
    },
    "viewer": {
        "documents.view",
        "documents.download",
    },
}

DEFAULT_ROLE_NAMES = {
    "admin": ("Admin", "Tenant administrator"),
    "member": ("Member", "Can upload and use documents"),
    "viewer": ("Viewer", "Read-only document access"),
}


def create_permissions_roles_and_assign_memberships(apps, schema_editor) -> None:
    tenant_model = apps.get_model("tenancy", "Tenant")
    permission_model = apps.get_model("accounts", "TenantPermission")
    role_model = apps.get_model("accounts", "TenantRole")
    membership_model = apps.get_model("accounts", "TenantMembership")

    permission_by_code = {}
    for code, label, category, sort_order in PERMISSIONS:
        permission, _created = permission_model.objects.update_or_create(
            code=code,
            defaults={
                "label": label,
                "category": category,
                "sort_order": sort_order,
                "description": "",
            },
        )
        permission_by_code[code] = permission

    for tenant in tenant_model.objects.all():
        roles_by_slug = {}
        for slug, (name, description) in DEFAULT_ROLE_NAMES.items():
            role, _created = role_model.objects.get_or_create(
                tenant=tenant,
                slug=slug,
                defaults={
                    "name": name,
                    "description": description,
                    "is_system_role": True,
                    "is_active": True,
                },
            )
            role.permissions.set(
                permission_by_code[code] for code in DEFAULT_ROLE_PERMISSIONS[slug]
            )
            roles_by_slug[slug] = role

        for membership in membership_model.objects.filter(tenant=tenant):
            legacy_role = membership.role or "viewer"
            role = roles_by_slug.get(legacy_role, roles_by_slug["viewer"])
            membership.role_ref = role
            membership.save(update_fields=["role_ref"])


def reverse_to_legacy_role_strings(apps, schema_editor) -> None:
    membership_model = apps.get_model("accounts", "TenantMembership")
    for membership in membership_model.objects.select_related("role_ref"):
        membership.role = membership.role_ref.slug if membership.role_ref_id else "viewer"
        membership.save(update_fields=["role"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["category", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="TenantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("is_system_role", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="tenantrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="accounts.tenantpermission",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="role_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.tenantrole",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrole",
            index=models.Index(
                fields=["tenant", "is_active"],
                name="accounts_te_tenant__36a63e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"),
                name="unique_tenant_role_slug",
            ),
        ),
        migrations.RunPython(
            create_permissions_roles_and_assign_memberships,
            reverse_code=reverse_to_legacy_role_strings,
        ),
        migrations.RemoveIndex(
            model_name="tenantmembership",
            name="accounts_te_tenant__5e1e1d_idx",
        ),
        migrations.RemoveField(
            model_name="tenantmembership",
            name="role",
        ),
        migrations.RenameField(
            model_name="tenantmembership",
            old_name="role_ref",
            new_name="role",
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.tenantrole",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant", "role"],
                name="accounts_te_tenant__43342c_idx",
            ),
        ),
    ]
