# Generated by Django 5.2.15 on 2026-07-06 21:10

from django.db import migrations, models


def copy_primary_role_to_roles(apps, schema_editor) -> None:
    membership_model = apps.get_model("accounts", "TenantMembership")
    for membership in membership_model.objects.exclude(role_id=None):
        membership.roles.add(membership.role_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_roles_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='multi_role_memberships', to='accounts.tenantrole'),
        ),
        migrations.RunPython(copy_primary_role_to_roles, migrations.RunPython.noop),
    ]
