# Generated by Django 5.2.15 on 2026-07-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenantrole_document_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrole',
            name='can_access_all_document_spaces',
            field=models.BooleanField(default=True),
        ),
    ]
