# Generated by Django 5.2.15 on 2026-07-07 20:30

import django.db.models.deletion
from django.db import migrations, models

import doksio.ingestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0009_documentmetadatafield_einvoice_source'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(choices=[('http_api', 'HTTP/API'), ('upload', 'Upload'), ('email', 'E-Mail'), ('folder', 'Ordner')], default='http_api', max_length=40)),
                ('token', models.CharField(default=doksio.ingestion.models.generate_import_token, max_length=120)),
                ('auto_start_ocr', models.BooleanField(default=True)),
                ('extract_einvoice', models.BooleanField(default=True)),
                ('start_workflows', models.BooleanField(default=True)),
                ('default_tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='documents.documentspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['document_space__path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('received', 'Empfangen'), ('processing', 'In Verarbeitung'), ('imported', 'Importiert'), ('failed', 'Fehlgeschlagen')], default='received', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='documents.document')),
                ('document_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='documents.documentspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='tenancy.tenant')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ingestion.importsource')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='importsource',
            index=models.Index(fields=['tenant', 'source_type', 'is_active'], name='ingestion_i_tenant__6cd637_idx'),
        ),
        migrations.AddIndex(
            model_name='importsource',
            index=models.Index(fields=['tenant', 'document_space'], name='ingestion_i_tenant__09921c_idx'),
        ),
        migrations.AddIndex(
            model_name='importsource',
            index=models.Index(fields=['token'], name='ingestion_i_token_258f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_i_tenant__4bfdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'source', 'status'], name='ingestion_i_tenant__980559_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'document_space', 'received_at'], name='ingestion_i_tenant__e18d26_idx'),
        ),
    ]
