# Generated by Django 5.2.15 on 2026-07-26 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0028_alter_documenttitlerule_options_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('search_term', models.CharField(blank=True, max_length=255)),
                ('include_child_spaces', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_alarms', to='documents.documentspace')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_alarms', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='document_alarms', to='documents.documenttag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_alarms', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAlarmMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='alarms.documentalarm')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_matches', to='documents.document')),
            ],
            options={
                'ordering': ['-matched_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentalarm',
            index=models.Index(fields=['tenant', 'owner', 'is_active'], name='alarms_docu_tenant__cf4460_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentalarm',
            constraint=models.UniqueConstraint(fields=('tenant', 'owner', 'name'), name='alarms_unique_owner_name'),
        ),
        migrations.AddIndex(
            model_name='documentalarmmatch',
            index=models.Index(fields=['alarm', 'matched_at'], name='alarms_docu_alarm_i_543381_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentalarmmatch',
            constraint=models.UniqueConstraint(fields=('alarm', 'document'), name='alarms_unique_alarm_document'),
        ),
    ]
