# Generated by Django 5.2.15 on 2026-07-06 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(default='generic', max_length=80)),
                ('status', models.CharField(default='active', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_kind', models.CharField(choices=[('original', 'Original'), ('derivative', 'Derivative')], default='original', max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_files', to=settings.AUTH_USER_MODEL)),
                ('derivative_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='documents.documentfile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_files', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['document_id', 'file_kind', 'version'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'document_type'], name='documents_d_tenant__7b56de_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='documents_d_tenant__1461e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'created_at'], name='documents_d_tenant__1bffd8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['tenant', 'created_at'], name='documents_d_tenant__337f87_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['tenant', 'sha256'], name='documents_d_tenant__516225_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['tenant', 'file_kind'], name='documents_d_tenant__162feb_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.UniqueConstraint(fields=('document', 'file_kind', 'version'), name='unique_document_file_kind_version'),
        ),
    ]
