# Generated by Django 5.2.15 on 2026-07-06 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_spaces'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_tag_assignments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='documents.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.documenttag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tag_assignments', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['tag__name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'document', 'created_at'], name='documents_d_tenant__f66e7f_idx'), models.Index(fields=['tenant', 'created_at'], name='documents_d_tenant__8c3d93_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['tenant', 'name'], name='documents_d_tenant__3915b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_tenant_document_tag_slug'),
        ),
        migrations.AddIndex(
            model_name='documenttagassignment',
            index=models.Index(fields=['tenant', 'document'], name='documents_d_tenant__6cfaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttagassignment',
            index=models.Index(fields=['tenant', 'tag'], name='documents_d_tenant__b1bfec_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttagassignment',
            constraint=models.UniqueConstraint(fields=('document', 'tag'), name='unique_document_tag_assignment'),
        ),
    ]
