# Generated by Django 5.2.15 on 2026-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentmetadatafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
