# Generated by Django 5.2.15 on 2026-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title_source',
            field=models.CharField(choices=[('manual', 'Manuell'), ('filename', 'Dateiname'), ('ocr', 'OCR')], default='manual', max_length=20),
        ),
    ]
