# Generated by Django 5.2.15 on 2026-07-08 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_reports_permission'),
        ('documents', '0012_document_documents_d_tenant__4a07cd_idx_and_more'),
        ('tenancy', '0001_initial'),
        ('workflows', '0003_remove_workflowstep_requires_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['tenant', 'status', 'created_at', 'id'], name='workflows_w_tenant__ff79b7_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['tenant', 'completed_by', 'status', 'completed_at'], name='workflows_w_tenant__2cc288_idx'),
        ),
    ]
