# Generated by Django 5.2.15 on 2026-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_import_batch'),
        ('workflows', '0004_workflowtask_workflows_w_tenant__ff79b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='required_metadata_fields',
            field=models.ManyToManyField(blank=True, related_name='required_by_workflow_steps', to='documents.documentmetadatafield'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('task', 'Aufgabe'), ('approval', 'Freigabe'), ('complete_metadata', 'Daten vervollständigen')], default='task', max_length=40),
        ),
    ]
