# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_documentrelation"),
        ("workflows", "0005_workflowstep_required_metadata_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="min_related_documents",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="related_document_requires_completed_workflow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="required_related_document_spaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="relation_required_by_workflow_steps",
                to="documents.documentspace",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("task", "Aufgabe"),
                    ("approval", "Freigabe"),
                    ("complete_metadata", "Daten vervollständigen"),
                    (
                        "require_document_relation",
                        "Dokumentverknüpfung erforderlich",
                    ),
                ],
                default="task",
                max_length=40,
            ),
        ),
    ]
