# Generated by Codex on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0021_remove_documentrelation_note"),
        ("workflows", "0006_workflowstep_document_relation_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="relation_picker_default_document_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentspace",
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="relation_picker_default_include_child_spaces",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="relation_picker_default_workflow_status",
            field=models.CharField(
                choices=[
                    ("any", "Alle"),
                    ("open", "Offener Workflow"),
                    ("completed", "Workflows abgeschlossen"),
                    ("none", "Keine Workflows"),
                ],
                default="any",
                max_length=20,
            ),
        ),
    ]
