# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_workflowstep_relation_picker_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="relation_picker_filters_editable",
            field=models.BooleanField(default=True),
        ),
    ]
