# Generated by Django 5.2.15 on 2026-07-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_title_source'),
        ('tenancy', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='trigger_document_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_templates', to='documents.documentspace'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='trigger_include_child_spaces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['tenant', 'trigger_document_space'], name='workflows_w_tenant__476195_idx'),
        ),
    ]
