# Generated by Django 5.2.15 on 2026-07-06 21:43

from django.db import migrations, models


def migrate_comment_policy(apps, schema_editor):
    WorkflowStep = apps.get_model("workflows", "WorkflowStep")
    WorkflowStep.objects.filter(requires_comment=True).update(
        comment_policy="required",
    )
    WorkflowStep.objects.filter(requires_comment=False).update(
        comment_policy="optional",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowtemplate_trigger_document_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='comment_policy',
            field=models.CharField(choices=[('disabled', 'Kein Kommentar'), ('optional', 'Kommentar optional'), ('required', 'Kommentar erforderlich')], default='optional', max_length=20),
        ),
        migrations.RunPython(
            migrate_comment_policy,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='requires_comment',
        ),
    ]
