# Generated by Django 5.2.15 on 2026-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantmembership_roles'),
        ('documents', '0006_document_title_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrole',
            name='document_spaces',
            field=models.ManyToManyField(blank=True, related_name='access_roles', to='documents.documentspace'),
        ),
    ]
