# Generated by Django 5.2.15 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_reports_permission"),
        ("documents", "0015_documentcomment_mentioned_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="document_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="documents.documentcomment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("workflow_task_created", "Workflow-Aufgabe erstellt"),
                    ("document_comment_mention", "Kommentar-Erwähnung"),
                ],
                max_length=80,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["document_comment", "recipient"],
                name="accounts_no_documen_a51d99_idx",
            ),
        ),
    ]
