# Generated by Django 5.2.15 on 2026-07-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_comment_mention_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_documen_691434_idx',
            old_name='accounts_no_documen_a51d99_idx',
        ),
    ]
