# Generated by Django 5.2.15 on 2026-07-20 18:29

from django.db import migrations, models

import doksio.accounts.models


def populate_notification_preferences(apps, schema_editor) -> None:
    user_profile_model = apps.get_model("accounts", "UserProfile")
    for profile in user_profile_model.objects.all():
        preferences = doksio.accounts.models.default_notification_preferences()
        preferences["workflow_task_created"]["in_app"] = (
            profile.notifications_enabled and profile.workflow_notifications_enabled
        )
        preferences["workflow_started"]["in_app"] = (
            profile.notifications_enabled and profile.workflow_notifications_enabled
        )
        preferences["document_comment_mention"]["in_app"] = (
            profile.notifications_enabled and profile.mention_notifications_enabled
        )
        if not profile.notifications_enabled:
            for channels in preferences.values():
                channels["in_app"] = False
        profile.notification_preferences = preferences
        profile.save(update_fields=["notification_preferences"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_document_batch_import_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=doksio.accounts.models.default_notification_preferences),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workflow_started', 'Workflow gestartet'), ('workflow_task_created', 'Workflow-Aufgabe erstellt'), ('document_comment_mention', 'Kommentar-Erwähnung'), ('import_failed', 'Importfehler')], max_length=80),
        ),
        migrations.RunPython(
            populate_notification_preferences,
            migrations.RunPython.noop,
        ),
    ]
