# Generated by Django 5.2.15 on 2026-07-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_document_split_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workflow_started', 'Workflow gestartet'), ('workflow_task_created', 'Workflow-Aufgabe erstellt'), ('document_comment_mention', 'Kommentar-Erwähnung'), ('import_failed', 'Importfehler'), ('document_alarm', 'Dokumentenalarm')], max_length=80),
        ),
    ]
