# Generated by Django 5.2.15 on 2026-07-26 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_notification_notification_type'),
        ('documents', '0028_alter_documenttitlerule_options_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_view_histories', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_viewed_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'user', '-last_viewed_at'], name='accounts_do_tenant__5581c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'document'), name='accounts_unique_document_view')],
            },
        ),
    ]
