# Generated by Django 5.2.15 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_document_reminder_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrole',
            name='is_public_group',
            field=models.BooleanField(default=False),
        ),
    ]
