# Generated by Django 5.2.15 on 2026-07-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_documentmetadatafield'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Wartet'), ('running', 'Läuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(blank=True, max_length=40)),
                ('extracted_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ocr_jobs', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='documents.documentfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ocr_ocrjob_tenant__e82e45_idx'), models.Index(fields=['tenant', 'document_file', 'created_at'], name='ocr_ocrjob_tenant__4236c9_idx'), models.Index(fields=['tenant', 'created_at'], name='ocr_ocrjob_tenant__873ef1_idx')],
            },
        ),
    ]
