# Generated by Django 5.2.15 on 2026-07-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0012_document_documents_d_tenant__4a07cd_idx_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filenames_text', models.TextField(blank=True)),
                ('tags_text', models.TextField(blank=True)),
                ('comments_text', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('metadata_text', models.TextField(blank=True)),
                ('combined_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_search_indexes', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['document_id'],
                'indexes': [models.Index(fields=['tenant', 'document'], name='search_docu_tenant__6916aa_idx'), models.Index(fields=['tenant', 'updated_at'], name='search_docu_tenant__ff8338_idx'), models.Index(fields=['tenant', 'title'], name='search_docu_tenant__391cbc_idx')],
            },
        ),
    ]
