# Generated by Django 5.2.15 on 2026-07-08 10:53

import django.contrib.postgres.search
from django.db import migrations


def create_postgres_search_vector_index(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS search_document_search_vector_gin
        ON search_documentsearchindex
        USING gin (search_vector)
        """
    )
    schema_editor.execute(
        """
        UPDATE search_documentsearchindex
        SET search_vector =
            setweight(to_tsvector('german', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('german', coalesce(filenames_text, '')), 'B') ||
            setweight(to_tsvector('german', coalesce(tags_text, '')), 'B') ||
            setweight(to_tsvector('german', coalesce(metadata_text, '')), 'B') ||
            setweight(to_tsvector('german', coalesce(comments_text, '')), 'C') ||
            setweight(to_tsvector('german', coalesce(ocr_text, '')), 'D')
        """
    )


def drop_postgres_search_vector_index(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS search_document_search_vector_gin")


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchindex',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            create_postgres_search_vector_index,
            reverse_code=drop_postgres_search_vector_index,
        ),
    ]
